/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentActivityCellRouteImport } from './routes/student-activity-cell'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PlacementCellRouteImport } from './routes/placement-cell'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AccreditationRouteImport } from './routes/accreditation'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const StudentActivityCellRoute = StudentActivityCellRouteImport.update({
  id: '/student-activity-cell',
  path: '/student-activity-cell',
  getParentRoute: () => rootRouteImport,
})
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
})
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
})
const PlacementCellRoute = PlacementCellRouteImport.update({
  id: '/placement-cell',
  path: '/placement-cell',
  getParentRoute: () => rootRouteImport,
})
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
})
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
})
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
})
const AccreditationRoute = AccreditationRouteImport.update({
  id: '/accreditation',
  path: '/accreditation',
  getParentRoute: () => rootRouteImport,
})
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccreditationRoute: AccreditationRoute,
  AdministrationRoute: AdministrationRoute,
  ContactUsRoute: ContactUsRoute,
  InfrastructureRoute: InfrastructureRoute,
  PlacementCellRoute: PlacementCellRoute,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentActivityCellRoute: StudentActivityCellRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
